# Generated by Django 3.1.6 on 2021-03-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=4)),
                ('chapter_name', models.CharField(max_length=40)),
                ('Lavel', models.CharField(max_length=4)),
                ('disciption', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=3)),
                ('topic_Key', models.CharField(max_length=40)),
                ('QuestionText', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Stud_class', models.CharField(max_length=4)),
                ('medium', models.CharField(max_length=3)),
                ('course', models.CharField(max_length=4)),
                ('coin', models.CharField(max_length=4)),
                ('weight', models.CharField(max_length=4)),
            ],
        ),
    ]
