# Generated by Django 3.1.6 on 2021-03-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GKQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionA', models.CharField(max_length=50)),
                ('optionB', models.CharField(max_length=50)),
                ('optionC', models.CharField(max_length=50)),
                ('optionD', models.CharField(max_length=50)),
                ('disciption', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1)),
                ('topic', models.CharField(max_length=40)),
                ('QuestionText', models.CharField(max_length=1000)),
            ],
        ),
    ]
